CREATE TABLE MNG.PUBLIC.ADWORDS_REPORTS( REPORT_NAME string,where_clause string ,Loading_data_offset string ,update_timestamp timestamp);

insert into MNG.PUBLIC.ADWORDS_REPORTS VALUES('AD_PERFORMANCE_REPORT','WHERE Impressions > 0','LAST_30_DAYS',current_date);
insert into MNG.PUBLIC.ADWORDS_REPORTS VALUES('ADGROUP_PERFORMANCE_REPORT','WHERE Impressions > 0','LAST_30_DAYS',current_date);
insert into MNG.PUBLIC.ADWORDS_REPORTS VALUES('CAMPAIGN_PERFORMANCE_REPORT','WHERE Impressions > 0','LAST_30_DAYS',current_date);
insert into MNG.PUBLIC.ADWORDS_REPORTS VALUES('BUDGET_PERFORMANCE_REPORT','WHERE Impressions > 0','YESTERDAY',current_date);
insert into MNG.PUBLIC.ADWORDS_REPORTS VALUES('SEARCH_QUERY_PERFORMANCE_REPORT','WHERE Impressions > 0','LAST_30_DAYS',current_date);
insert into MNG.PUBLIC.ADWORDS_REPORTS VALUES('PLACEMENT_PERFORMANCE_REPORT','WHERE Impressions > 0','LAST_30_DAYS',current_date);
insert into MNG.PUBLIC.ADWORDS_REPORTS VALUES('KEYWORDS_PERFORMANCE_REPORT','WHERE Impressions > 0 AND IsNegative IN [true, false]','LAST_30_DAYS',current_date);
insert into MNG.PUBLIC.ADWORDS_REPORTS VALUES('CLICK_PERFORMANCE_REPORT','','YESTERDAY',current_date);
insert into MNG.PUBLIC.ADWORDS_REPORTS VALUES('URL_PERFORMANCE_REPORT','WHERE Impressions > 0','LAST_30_DAYS',current_date);
insert into MNG.PUBLIC.ADWORDS_REPORTS VALUES('CRITERIA_PERFORMANCE_REPORT','WHERE Impressions > 0','LAST_30_DAYS',current_date);