
------merge stg.adwords.fact_adwords_performance to dwh 		  
		  
		  
merge into dwh.adwords.fact_adwords_performance t1 using stg.adwords.fact_adwords_performance t2 on t1.business_date = t2.business_date and
                                                                                                    t1.account_id = t2.account_id and
                                                                                                    t1.campaign_id = t2.campaign_id and
                                                                                                    t1.ad_group_id = t2.ad_group_id and
                                                                                                    t1.ad_id = t2.ad_id and
                                                                                                    t1.device = t2.device 

    when matched  then update set t1.conversions = t2.conversions, 
                                  t1.total_conv_value = t2.total_conv_value , 
                                  t1.conversion_rate=t2.conversion_rate,
                                  t1.roi=t2.roi,
                                  t1.aov=t2.aov,
								  t1.update_timestamp = current_timestamp,
								  t1.snapshot_timestamp = t2.snapshot_timestamp
    when not matched then insert (create_timestamp,
                                  business_date,
                                  account_id,
                                  account_name,
                                  currency,
                                  campaign_id,
                                  campaign_name,
                                  campaign_status,
                                  campaign_type,
                                  bidding_strategy_id,
                                  bidding_strategy_name,
                                  bidding_strategy_type,
                                  labels_id_campaign,
                                  labels_campaign,
                                  budget,
                                  total_budget,
                                  budget_name,
                                  ad_group_id,
                                  ad_group_name,
                                  ad_group_status,
                                  ad_group_type,
                                  labels_id_ad_group,
                                  labels_ad_group,
                                  max_cpc_bid,
                                  max_cpm_bid,
                                  max_cpv_bid,
                                  ad_id,
                                  ad_type,
								  ad_status,
                                  ad_approval_status,
                                  is_automated_ad,
                                  ad_business_name,
                                  device_preference,
                                  final_url,
                                  mobile_final_url,
                                  ad_display_url,
                                  headline,
                                  headline_part_1,
                                  headline_part_2,
                                  description,
                                  description_part_1,
                                  description_part_2,
                                  long_headline,
                                  promotion_text,
                                  price_prefix,
                                  image_id,
                                  square_image_id,
                                  logo_id,
                                  landscape_logo_id,
                                  call_to_action_text,
                                  tracking_template,
                                  custom_parameter,
                                  path_1,
                                  path_2,
                                  phone_number,
                                  short_headline,
                                  image_headline,
                                  image_description,
                                  labels_ad_id,
                                  labels_ad,
                                  device,
                                  cost,
                                  clicks,
                                  impressions,
                                  views,
                                  conversions,
                                  total_conv_value,
                                  avg_cpc,
                                  avg_cpm,
                                  avg_cpv,
                                  ctr,
                                  cpa,
                                  conversion_rate,
                                  roi,
                                  aov,
                                  atg_conversions,
                                  atg_order_val,
								  snapshot_timestamp) values (current_timestamp,
																business_date,
																account_id,
																account_name,
																currency,
																campaign_id,
																campaign_name,
																campaign_status,
																campaign_type,
																bidding_strategy_id,
																bidding_strategy_name,
																bidding_strategy_type,
																labels_id_campaign,
																labels_campaign,
																budget,
																total_budget,
																budget_name,
																ad_group_id,
																ad_group_name,
																ad_group_status,
																ad_group_type,
																labels_id_ad_group,
																labels_ad_group,
																max_cpc_bid,
																max_cpm_bid,
																max_cpv_bid,
																ad_id,
																ad_type,
																ad_status,
																ad_approval_status,
																is_automated_ad,
																ad_business_name,
																device_preference,
																final_url,
																mobile_final_url,
																ad_display_url,
																headline,
																headline_part_1,
																headline_part_2,
																description,
																description_part_1,
																description_part_2,
																long_headline,
																promotion_text,
																price_prefix,
																image_id,
																square_image_id,
																logo_id,
																landscape_logo_id,
																call_to_action_text,
																tracking_template,
																custom_parameter,
																path_1,
																path_2,
																phone_number,
																short_headline,
																image_headline,
																image_description,
																labels_ad_id,
																labels_ad,
                                                                device,
																cost,
																clicks,
																impressions,
																views,
																conversions,
																total_conv_value,
																avg_cpc,
																avg_cpm,
																avg_cpv,
																ctr,
																cpa,
																conversion_rate,
																roi,
																aov,
																atg_conversions,
																atg_order_val,
																snapshot_timestamp);